---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- My First Group:
    - Vikunja:
        href: {{HOMEPAGE_VAR_VIKUNJA_URL}}
        widget:
          type: vikunja
          url: {{HOMEPAGE_VAR_VIKUNJA_URL}}
          key: {{HOMEPAGE_VAR_VIKUNJA_KEY}}
          enableTaskList: false
    - Nginx Proxy Manager:
        href: {{HOMEPAGE_VAR_NPM_URL}}
        widget:
          type: npm
          url: {{HOMEPAGE_VAR_NPM_URL}}
          username: {{HOMEPAGE_VAR_NPM_USER}}
          password: {{HOMEPAGE_VAR_NPM_PASSWORD}}
